use error formatting given by github actions

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -26,7 +26,7 @@ jobs:
         run: |
           curl -sL https://api.github.com/repos/w3c/respec/pulls/${{ github.event.pull_request.number }}/files -o /tmp/pr_files.json
           cat /tmp/pr_files.json | jq -r '.[].filename' | grep -qE "^builds/" || exit 0
-          echo 'Uh oh! builds/ was changed.'; exit 1
+          echo "::error::Uh oh! builds/ was changed."; exit 1
       - uses: actions/setup-node@v2
         with:
           node-version: 14
